/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconEdi: typeof import('@element-plus/icons-vue')['Edi']
    ElIconEdit: typeof import('@element-plus/icons-vue')['Edit']
    IEpAddLocation: typeof import('~icons/ep/add-location')['default']
    IEpAddPear: typeof import('~icons/ep/add-pear')['default']
    IEpApple: typeof import('~icons/ep/apple')['default']
    IEpMapLocation: typeof import('~icons/ep/map-location')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
